#!/bin/sh
#-*- scheme -*-
#
#    Copyright (C) 2012 Greg Benison
#   
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#   
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#   
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#  

export GUILE_LOAD_PATH=$GUILE_LOAD_PATH:`pwd`;
export LTDL_LIBRARY_PATH=$LTDL_LIBRARY_PATH:`pwd`;
export GUILE_WARN_DEPRECATED=no;
# exec guile -s $0 2>/dev/null
exec guile -s $0 2>>guile-error.log

!#

(use-modules (taubatron)
	     (sxml simple)
	     (www server-utils big-dishing-loop))

(define (sxml->text sxml)
  (with-output-to-string
    (lambda () (sxml->xml sxml))))

(define (tt-handler M upath)
  (M #:set-reply-status:success)
  (M #:add-header #:Content-type "text/plain")
  (M #:add-content
     (sxml->text '(p "It works!!!")))
  (M #:send-reply)
  #t)

(define server
  (make-big-dishing-loop
   #:method-handlers `((GET . ,tt-handler))))

(define server-sock (socket PF_INET SOCK_STREAM 0))
(bind server-sock AF_INET INADDR_ANY 8081)
(server server-sock)
